### ISSUE TITLE
Images Fade to White

### ISSUE THREAD

**Issue by Mottie** [CSS-Tricks/AnythingSlider#421]
@Ephezius : Hello - love the slider! I have everything finally set the way I want it, but the problem is that when the first image fades it fades to white... then the next image abruptly pops up as visible. I did some testing and it looks like the current image is on top of a div with a background image and then fades out... the next image must be z-indexed behind my div-wrapper background image and it pops into view when the fade is done.

I played with z-index: -1 for my background divs, but it messes with the navigation and mouse over events firing.

Any help is much appreciated.

E

Mottie: Hi Ephezius! It sounds like there might be some css interfering with the fading... do you happen to have a live demo of this happening?

**Comment by dimiras** [comment]
Im still having this issue even when using the latest version. It works ok when I swipe back but not when swiping forward
