### ISSUE TITLE
First time loading delay times are wrong.

### ISSUE THREAD

**Issue by Vitoko** [CSS-Tricks/AnythingSlider#536]
Hi @Mottie , i can clarify my problem better now:

In the first time i load the slideshow, the first slide does not have the correct delay time, but the rest of the slides have the correct delay time. But, on the next round they all have the right delay time. 

I use the method 2: https://github.com/CSS-Tricks/AnythingSlider/wiki/FAQ#wiki-delay

i don't know why this occur.

Thanks for helping me!

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
