### ISSUE TITLE
Add clone withDataAndEvents option (infiniteSlides)

### ISSUE THREAD

**Issue by ckng** [CSS-Tricks/AnythingSlider#587]
For infiniteSlides, when the slide items are attached to other javascript such as popup, the data and events are not copied. It would be nice to have an option to pass to AnythingSlider to indicate if we want to .clone(withDataAndEvents).

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
