### ISSUE TITLE
Extra Blank Slide at End When Setting showMultiple = X and infiniteSlides = false

### ISSUE THREAD

**Issue by evanrose** [CSS-Tricks/AnythingSlider#602]
Note: http://jsfiddle.net/mXphJ/1/

That said, setting stopAtEnd = true corrects this behavior http://jsfiddle.net/QsWX2/ 

If this isn't a bug, more documentation about these options might be needed.

**Comment by yashyashwanth** [comment]
im facing the same issue too.

**Comment by Mottie** [comment]
Related: https://github.com/CSS-Tricks/AnythingSlider/issues/659

**Comment by JamyGolden** [comment]
https://github.com/CSS-Tricks/AnythingSlider/commit/2d36fc2f4ddaa033c0cbe471a9825582c427e8a8
