### ISSUE TITLE
Using with MediaWiki. Slider in Firefox not displayed correctly.

### ISSUE THREAD

**Issue by UksusoFF** [CSS-Tricks/AnythingSlider#621]
Hi!
I want use this slider with MediaWiki 1.22. It's have build-in jQuery 1.8.3.
I've create template and it's correctly display in Chrome and IE, but Firefox not display text after embed video, example: http://wiki.rock63.ru/Template:VideoGallery
![sample](https://cloud.githubusercontent.com/assets/1931442/3752727/fdccf460-180a-11e4-92d1-9744df8094b8.png)
Whats wrong?

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
