### ISSUE TITLE
How to remove numbered tabs & start/stop button

### ISSUE THREAD

**Issue by JuliaT72** [CSS-Tricks/AnythingSlider#633]
I am using the simple version on a site but I don’t want to have the bottom tabs or start/stop showing – how do I remove that?

For a quick fix I changed it on here http://www.dripool.co.uk/news-test.html with most of it hidden but the top shadow still shows - And I can’t find the css which causes the shadow part

Also, why does the page revert to http://www.dripool.co.uk/news-test.html#&panel1-1 when you go to it and how can this be stopped?

**Comment by Mottie** [comment]
Hi @JuliaT72!

To remove both the navigation tabs and the start/stop tab, set the following options ([documentation reference](https://github.com/CSS-Tricks/AnythingSlider/wiki/Appearance-Options#buildnavigation-true) &amp; [demo](http://jsfiddle.net/ycUB6/9814/)):

```js
$('#slider').anythingSlider({
    // If true, builds a list of anchor links to link to each panel
    buildNavigation: false,
    // If true, builds the start/stop button
    buildStartStop: false
});
```

I'm not 100% sure what you mean by the page reverting when you go to it. Are you referring to the `#&panel1-1` in the url? You can turn that off by setting the [`hashTags` option](https://github.com/CSS-Tricks/AnythingSlider/wiki/Navigation-options#hashtags) to `false`.

**Comment by JuliaT72** [comment]
Hi,

Thanks for that but I am not sure where I change it, what file do I find
these in??

Julia

From:  Rob G <notifications@github.com>
Reply-To:  CSS-Tricks/AnythingSlider
<reply+00a53f47746a3a4bec4d5f470dec81bcaeb022001fc3852392cf0000000110e88e639
2a169ce035c1c4f@reply.github.com>
Date:  Tuesday, 3 February 2015 14:25
To:  CSS-Tricks/AnythingSlider <AnythingSlider@noreply.github.com>
Cc:  JuliaT72 <julia@juliandesigns.es>
Subject:  Re: [AnythingSlider] How to remove numbered tabs & start/stop
button (#633)


Hi @JuliaT72 <https://github.com/JuliaT72> !

To remove both the navigation tabs and the start/stop tab, set the following
options (documentation reference
<https://github.com/CSS-Tricks/AnythingSlider/wiki/Appearance-Options#buildn
avigation-true>  & demo <http://jsfiddle.net/ycUB6/9814/> ):

$('#slider').anythingSlider({
    // If true, builds a list of anchor links to link to each panel
    buildNavigation: false,
    // If true, builds the start/stop button
    buildStartStop: false
});
I'm not 100% sure what you mean by the page reverting when you go to it. Are
you referring to the #&panel1-1 in the url? You can turn that off by setting
the hashTags option
<https://github.com/CSS-Tricks/AnythingSlider/wiki/Navigation-options#hashta
gs>  to false.

‹
Reply to this email directly or view it on GitHub
<https://github.com/CSS-Tricks/AnythingSlider/issues/633#issuecomment-726494
02> .

**Comment by Mottie** [comment]
On your main page `news-test.html` you'll find this block:

```html
	<script>
		// DOM Ready
		$(function(){
			$('#slider').anythingSlider();
		});
	</script>
```

change it to:

```html
	<script>
		// DOM Ready
		$(function(){
			$('#slider').anythingSlider({
				buildNavigation: false,
				buildStartStop: false
			});
		});
	</script>
```

**Comment by JuliaT72** [comment]
That¹s great thanks for that

How about where to change the hashtag?


From:  Rob G <notifications@github.com>
Reply-To:  CSS-Tricks/AnythingSlider
<reply+00a53f4772ad5b79134e6588ec19ccc98eeb1977f4667e1992cf0000000110e8adb79
2a169ce035c1c4f@reply.github.com>
Date:  Tuesday, 3 February 2015 16:39
To:  CSS-Tricks/AnythingSlider <AnythingSlider@noreply.github.com>
Cc:  JuliaT72 <julia@juliandesigns.es>
Subject:  Re: [AnythingSlider] How to remove numbered tabs & start/stop
button (#633)


On your main page news-test.html you'll find this block:

    <script>        // DOM Ready        $(function(){
$('#slider').anythingSlider();        });    </script>
change it to:

    <script>        // DOM Ready        $(function(){
$('#slider').anythingSlider({                buildNavigation: false,
buildStartStop: false            });        });    </script>
‹
Reply to this email directly or view it on GitHub
<https://github.com/CSS-Tricks/AnythingSlider/issues/633#issuecomment-726720
21> .

**Comment by Mottie** [comment]
No problem!
