### ISSUE TITLE
HTML5 videos file size and autoplay trouble

### ISSUE THREAD

**Issue by Vitoko** [CSS-Tricks/AnythingSlider#636]
I am using AnythingSlider to play only mp4 files from my localhost and sometimes the videos get frozen, specially when they are heavier (100 or 500 MB) and more often with autoplay. AnythingSlider support any file size in mp4 format?
P.S. It works better when i release the browser cache.
Does RAM memory have anything to do with it? Would it be fine having Windows 7, Google Chrome and 4GB of RAM memory?

**Comment by Mottie** [comment]
Hi @Vitoko!

HTML5 video limitations are all based on the browser. AnythingSlider only wraps the video tag and manipulates it.

**Comment by Vitoko** [comment]
Ok,  i will try again with a clean browser, thanks, it is a very useful tool!
