### ISSUE TITLE
Getting number of panels to change depending on browser window size

### ISSUE THREAD

**Issue by CBCR** [CSS-Tricks/AnythingSlider#637]
I am having trouble with getting the slider to work because I want the number of panels to show based on the browser window size.  The options I want are:
resizeContents: false,
buildNavigation: false,
buildStartStop: false,
infiniteSlides: false,
stopAtEnd: true,

these are work fine when showMultiple: 3  However, I want it to show only 1 or 2 panels as the browser window gets smaller, so I added the script from  http://jsfiddle.net/Mottie/ycUB6/670/ but it does not work.  

If I take that fiddle and add:
infiniteSlides: false,
stopAtEnd: true 
it works.  http://jsfiddle.net/CBCRwebmaster/4j58sb3r/1/

If I take that fiddle and add:
buildNavigation: false,
buildStartStop: false
it works. http://jsfiddle.net/CBCRwebmaster/4j58sb3r/3/

If I take that fiddle and add: 
infiniteSlides: false,
stopAtEnd: true, 
buildNavigation: false,
buildStartStop: false
it breaks.  http://jsfiddle.net/CBCRwebmaster/4j58sb3r/4/

Also, if I take the fiddle and add just resizeContents: false it breaks.  http://jsfiddle.net/CBCRwebmaster/4j58sb3r/2/

I am new at this, so it is quite possible I am doing something wrong.

**Comment by Mottie** [comment]
Hi @CBCR!

Can you define what you mean by "it breaks" and "does not work"?

I tried the last demo and I do see a problem e with the images maintaining a `max-width` setting when really narrowing down in width. You can solve this by wrapping the images in a span - because a width setting on a span doesn't do anything unless it is set to `display:inline-block` - [updated demo](http://jsfiddle.net/Mottie/4j58sb3r/5/).

**Comment by CBCR** [comment]
Thanks for getting back to me so quickly.  With this one http://jsfiddle.net/CBCRwebmaster/4j58sb3r/4/  I currently have it up with the result of width = 843; multi = 2 but as I click through sometimes I am seeing one panel and sometimes I am seeing two panels.  Likewise at width = 1024; multi = 3

I tried your demo and it is not working quite right.  It works fine when the browser window is only wide enough for one panel.  When the browser window is wide enough for 2 or 3 panels it works until the last of the five photos is showing (bacon) and then when you click on the right arrow the number of panels decreases until you are left with just one panel.  Once you are down to just the one panel and click again on the right arrow, you see 2 or 3 panels.  And, once you are down to just the one panel and click the left arrow it expands one panel at a time until it reaches the number of panels that are suppose to be showing.

With this one http://jsfiddle.net/CBCRwebmaster/4j58sb3r/4/  it works fine with just one panel showing.  If you expand the window so 2 or 3 panels are showing and click the right arrow all the way through the photos, sometimes the right arrow disappears and sometimes it doesn’t.  If at that point you then click on the left arrow, when you get to the first panel the left arrow does not disappear.  

Also, sometimes when you narrow and then expand the window, all you see in the result are two arrows and the two green borders making one thick line, no images.  If you click on the right arrow the images will show.  This is hard to replicate and might only occur when you first open the demo.  If I keep changing the window size, the images always show, so I am not sure if it will be a problem in a live website.

Earlier I forgot to make a demo with all 5 options.  It is now at http://jsfiddle.net/CBCRwebmaster/4j58sb3r/6/  I shrunk the window and expanded it and got the same two arrows with just the green line and no images.  Clicked on the right arrow and the images appeared.  I am now at width = 533; multi = 1 but I am seeing two images. (I actually think the width is larger than 533.)  I can click all the way through forwards and backwards, I always only see two images, but the arrows do not disappear.  At width = 997; multi = 3, I always see three images, but the arrows do not disappear.  And if I shrink down the window to see just one image, the arrows do not disappear.

**Comment by CBCR** [comment]
Turns out that if I use all 5 options and also change the opacity of the arrows in the css using
.anythingSlider .arrow.disabled {
    display: block !important;
    opacity: 0.5;
    filter: alpha(opacity=50);
}

the arrows do exactly what they are suppose to do.  I actually prefer that option to having them completely disappear.  And the number of images works as it should.  However, I still have the problem with sometimes seeing just the arrows and the fat green border when resizing the window and have to click on an arrow to bring up the images.

http://jsfiddle.net/CBCRwebmaster/4j58sb3r/7/

**Comment by Mottie** [comment]
I can't duplicate the issue you're reporting. When does the slider only show the arrows & green border? I resized the window in both Chrome & Firefox and had no issues.

I do think this might not be a real issue anyway... not many people resize their browser over & over... maybe this "might" be an issue on a mobile device when switching orientation.

**Comment by CBCR** [comment]
Yes, it is one of those weird, intermittent problems that is hard to duplicate.  I am using Safari, so maybe that is where the problem exists.  I was thinking about just leaving it because like you said, not many people keep changing the size of their window.  I’ll try uploading everything to my website and then testing it on my iPhone and iPad to see if it is a real issue or not.

Is it possible to have multiple sliders on a page without having unique IDs?  I was thinking instead of <ul id=“slider1”> and <ul id=“slider2”> using <ul class=“slider1”> and <ul class=“slider2”> and then having the script read 

$(‘.slider1’).each(function() {
     $(this).anythingSlider({
        list the options
    });
});
    $(‘.slider2’).each(function() {
     $(this).anythingSlider({
        list the options
    });
});

That would allow me to have multiple instances of slider1 and slider2.  The sliders are all going to be manually navigated.  Basically it is just to allow people to look through a gallery of photos of a dog up for adoption and maybe view a video if there is one.  The same slider will get used to show the dog after adoption, so needing unique IDs for each slider would be a pain.  Having only 3 sliders just to have different heights and widths and I would choose the one that best fits for the size of the photos that get submitted.  Not sure I can make this work though because I get all different size images submitted and I am trying to limit how much cropping I have to do.

**Comment by CBCR** [comment]
I put it up live at http://www.cbcr.org/anythingslider2.html  The issue I am having is that when it first comes up, macbook or iPad, it only displays one photo.  When you resize the browser, it shows the correct number of photos.  Also, I think the issue with the arrows and the line may be tied to resizing the browser too quickly.  If I do it slower, it does not happen.  More importantly, when I rotate the iPad I do not have the problem, it will always show two or three photos depending on orientation.  So the issue remaining is to get the proper number of photos to show when you first open the page.

**Comment by Mottie** [comment]
At the very bottom of your code (under the code that initializes AnythingSlider), add the following to make sure the `checkWidth` code is run:

```js
$(window).resize();
```

If that doesn't work, then wrap all of your code inside of a window load function:

```js
$(window).load(function(){
    // add all code inside this function
});

**Comment by CBCR** [comment]
Thanks. I played with where to place $(window).resize(); and it is working now.  

Wow, I have no idea what happened to yesterday's post regarding multiple sliders - words are missing and the format is wonky.  Basically, I wanted to know if there was a way to have multiple sliders on a page without each one having to have a unique ID.  These would just be manual sliders, showing only one photo at a time or perhaps a video.

**Comment by Mottie** [comment]
It works for me: http://jsfiddle.net/Mottie/ycUB6/9869/

**Comment by CBCR** [comment]
Fantastic!!  I am going to have to play around with it as this opens up a lot of possibilities.  

Thank you so much.
