### ISSUE TITLE
Hidden slider doesn't work when made active

### ISSUE THREAD

**Issue by jrtapper** [CSS-Tricks/AnythingSlider#639]
I am working on the dev site http://b2b.hitchfinderstores.com and I am using the anything slider tool in a couple of places on the home page.  The issue is with the large grid of part categories on the bottom of the page. 

When the page is initially loaded, the list grid of images arranged by "popularity" are displayed and the slider works to display the two panels of this grid.  The second group of these images arranged alphabetically is hidden (display: none;) and the slider styling is applied to it.  

When I un-hide the second group of images (using the drop down at the upper left corner) the slider width values are 0 .  Removing these seems to make the panel appear and sort of start to work.  

Is there a way that I can tell AnythingSlider to recompute these values when I make the second group active?

Thanks!

**Comment by Mottie** [comment]
Hi @jrtapper!

I'll test this when I get some more free time, but for now try re-initializing AnythingSlider without any options:

```js
$('#slider').anythingSlider();
```

That "should" refresh everything.

**Comment by jrtapper** [comment]
Thanks!!  

That works perfectly!
