### ISSUE TITLE
Anything slider is not working with jwplayer in safari 5.1.7 in windows 7

### ISSUE THREAD

**Issue by veenavg123** [CSS-Tricks/AnythingSlider#640]
Anything slider is not displaying videos via jwplayer in safari 5.1.7 in windows, but its working on chrome, mozilla and IE. Please suggest me a solution for safari browser.

**Comment by Mottie** [comment]
Hi @veenavg123!

Did you follow the [instructions from here](https://github.com/CSS-Tricks/AnythingSlider/wiki/Video#jwplayer)? If you did, are you seeing any errors in the browser console?

To be honest, this plugin hasn't been updated in so long, I would think there are better slider solutions out there.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
