### ISSUE TITLE
multiple sliders on same page

### ISSUE THREAD

**Issue by Stockie** [CSS-Tricks/AnythingSlider#641]
I have sliders on one page: #slider1 is called with some options.
#slider2 and #slider3 are called with the same options:
$(function(){
			$('#slider2,#slider3')
			    .anythingSlider({
                                 ...
)}

But the navigation bullets of #slider2 and #slider3 aren't working as it should. If i select a bullet of #slider2, all bullets of #slider3 become unselected. Can someone help me with this?

You can find the site here: www.robberterrico.be

**Comment by Mottie** [comment]
Hi @Stockie!

Please make sure the HTML being used is valid.

If that doesn't fix the issue, would you please duplicate the problem by modifying [this demo](http://jsfiddle.net/ebx1otr6/). Thanks

**Comment by Stockie** [comment]
Problem solved, i was a bit to eager in deleting lines in the CSS...

Another question:
Is it possible to bind a function to a button that searches for all the iframes on the page (youtube video's) and pauses them?

**Comment by Mottie** [comment]
Well, it depends. To make videos pause, all of them need to have the api active (especially YouTube). If all videos are inside of AnythingSliders, then it should not be that difficult since it has the video extension set up to control them.

To target a specific video in the slider to pause, you can use this code:

```js
// pause all YouTube videos inside of sliders
$('.all-sliders').each(function(){
	var index, len, video,
		data = $(this).data('AnythingSlider');
	if ( data && data.pages && data.video ) {
		len = data.pages;
		video = data.video.list;
		for ( index = 0; index < len; index++ ) {
			if ( video[ index ] && video[ index ].player ) {
				video[ index ].player.pauseVideo();
			}
		}
	}
});
```

It's not pretty because it wasn't set up to be used as an api. I tested the code above and it works.

**Comment by Stockie** [comment]
i don't really get this one.
What is '.all-sliders'? Where do i have to add this class?
also, what is the data.pages?
In any case, if i add this code to the fullpage.js event of moving to the next fullpageslide, the video in the Anythingslider on the first slide  keeps on playing...

**Comment by Mottie** [comment]
The `.allsliders` class is just a made up jQuery selector. I wanted to make it obvious that you can target more than one slider.

The [`data.pages`](https://github.com/CSS-Tricks/AnythingSlider/wiki/Callbacks-and-Events#sliderpages) is the total number of slides (or pages) in the slider.

Videos can only be controlled when you use a local host or the page is live on the internet. If you try to control a video locally (i.e. `file:///`), it won't work.

**Comment by Stockie** [comment]
ok, thanks. I will try it with the stie online
