### ISSUE TITLE
Youtube autoplay

### ISSUE THREAD

**Issue by OScartThomas** [CSS-Tricks/AnythingSlider#642]
I have a anythingslider with the autoplay function set to true.

So my youtube video's also have to play automaticcaly after the slide is loaded.
And must be restarted again if it comes back.

When I set the "autoplay" function of the youtube (iframe) to true, the video starts playing with the loading of the page. But it has jus to play whithin the right slide.

Can somebody help me with these settings?

Thanks in advance!

**Comment by Mottie** [comment]
If your slider only has ONE YouTube video, then this code will work ([demo](http://jsfiddle.net/Mottie/ycUB6/10210/)):

```js
$(function () {
  /* Use this method if ONLY ONE VIDEO exists in the slider */
  $('#slider')
    .anythingSlider()
    .anythingSliderVideo({
      youtubeParams: {
        autoplay: 1
      }
    });
});
```

If the slider has multiple videos, then you'll need to use a setTimeout (adjust the time as needed) to start playing the video in the currently visible panel ([demo](http://jsfiddle.net/Mottie/ycUB6/10209/))

```js
$(function () {
  /* Use this method if MULTIPLE VIDEOS exist in the slider */
  $('#slider')
    .anythingSlider()
    .anythingSliderVideo({
      onVideoInitialized: function (slider) {
        setTimeout(function () {
          var page = slider.currentPage - 1,
            control = slider.video.list[page] && slider.video.list[page];
          if (control) {
            control.player.playVideo();
          }
        }, 4000); // adjust this value as needed
      }
    });
});
```

**Comment by OScartThomas** [comment]
Hi,

Thanks for the answer.

I have the following code now:
<code>
$(function () {
    $('#slider')
    .anythingSlider({autoPlay: true, delay: 5000})
        .anythingSliderVideo({
        onVideoInitialized: function (slider) {
            setTimeout(function () {
                var page = slider.currentPage - 1,
                    control = slider.video.list[page] && slider.video.list[page];
                if (control) {
                    control.player.playVideo();
                }
            }, 5000);
        }
    });
});
</code>

This plays indeed at the first time the video (5 seconds after loading the page).
But how can i replay the video when the slide comes back and how do I have to set it with multiple videos?

For example to play this in loop:
<code>
<ul id="slider">
    <li><img src="" alt="" /></li>
    <li>
        <iframe width="560" height="315" src="http://www.youtube.com/embed/Bp5rn5ujmD0" frameborder="0" allowfullscreen></iframe>
    </li>
        <li><img src="" alt="" /></li>
    <li>
        <iframe width="560" height="315" src="http://www.youtube.com/embed/VgpAOkAfy4w" frameborder="0" allowfullscreen></iframe>
    </li>
</ul>
</code>

Thanks for the help!

Met vriendelijke groeten | Kind regards | Cordialement
[http://oscart.be/mail_footer/logo.png]


Thomas Laheye

President Kennedypark 3c

8500 Kortrijk

T. +32 56 98 08 28

M. +32 497 61 26 99


www.oscart.be<http://www.oscart.be>

thomas@oscart.be<mailto:thomas@oscart.be>



[http://oscart.be/mail_footer/ENVIRONMENT.jpg]Before you print think about the environment

[http://oscart.be/mail_footer/Facebook_Small_Transparent.png]<https://www.facebook.com/trsprojects>

**Comment by Mottie** [comment]
Add this before the document ready function ([demo](http://jsfiddle.net/Mottie/ycUB6/10211/)):

```js
/* play video when it comes into view, even after it has completed */
$.fn.anythingSliderVideo.services.youtube1.cont = function(slider, $vid, index) {
    slider.video.list[index].player && slider.video.list[index].player.playVideo();
};
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
