### ISSUE TITLE
FX demos aren't working

### ISSUE THREAD

**Issue by tiggsy** [CSS-Tricks/AnythingSlider#646]
https://css-tricks.github.io/AnythingSlider/demos.html is not a slider any more
I tried on Chrome and Firefox. As a Linux user, don't use any other browsers.

**Comment by Mottie** [comment]
Hi @tiggsy!

Thanks for reporting this! It looks like it due to the demo loading pages over `http` instead of `https`. I'll have it fixed shortly.

**Comment by tiggsy** [comment]
No worries. I've also had problems when I went over to https :)


PS. If you're interested in aromatherapy, herbs, supplements, sports
nutrition, food for special diets and similar things, you might be
interested in my site:
Frann's Alt.Health Shop <https://shop.frannsalthealth.com>
