### ISSUE TITLE
Video demo doesn't work

### ISSUE THREAD

**Issue by ddnetters** [CSS-Tricks/AnythingSlider#648]
On the video demo page the videos don't auto play, they just slide by. This happens on both ff and chrome for me.

**Comment by Mottie** [comment]
Hi @ddnetters!

I'm not sure what to tell you. I just looked at the video page and it looks fine to me.

Please look in the console for javascript errors. The only thing that I can think might have happened is that you might have been offline and jQuery or the script didn't load.

**Comment by ddnetters** [comment]
Hey @Mottie ,

These errors are in my console on chrome
http://pastebin.com/raw/D9ZeuVeP

**Comment by Mottie** [comment]
Thanks for reporting this. The video extension now uses https to access YouTube's api... the videos were always working for me, I just didn't look at the console LOL.
