### ISSUE TITLE
Photos are being rotated

### ISSUE THREAD

**Issue by thunder708** [CSS-Tricks/AnythingSlider#651]
hi i am using the anything slider and i have a few photos on it and forsome reason its rotate on eof my photos 90 degrees, any ideas?

**Comment by Mottie** [comment]
Hi @thunder708!

I have no idea. Maybe there is a stray css definition, or maybe even a [C.H.U.D.](https://en.wikipedia.org/wiki/C.H.U.D.)!

If you can't find the culprit, please modify [this demo](https://jsfiddle.net/Mottie/e1dwk69u/) to duplicate the issue; then I might be able to help troubleshoot the problem.

**Comment by thunder708** [comment]
For some reason it didnt like the fact the image was a jpg, changed it to a png and works fine

**Comment by Mottie** [comment]
Maybe the problem was with the Exif data? Check out this article:

http://www.techsupportalert.com/content/why-are-your-photos-upside-down.htm

**Comment by thunder708** [comment]
Hi, yes the Exif data was the issue! thank you so much for your help :)
