### ISSUE TITLE
Play button not Visible on IPad

### ISSUE THREAD

**Issue by Danhild** [CSS-Tricks/AnythingSlider#655]

**Comment by Danhild** [comment]
I have solved it by coincident:

Just put
<link rel="stylesheet" href="../DA/mediaelement/mediaelementplayer.css" />
in the top of all css links
If you place it as the first line of css links -it works !

-Also works for MediaElementPlayer !

Hope you can use it also

Have a good button !

**Comment by Mottie** [comment]
Hi @Danhild!

I don't own an "i"-anything, so any help you can provide in troubleshooting would be awesome

**Comment by Mottie** [comment]
LOL ok then 😁
