### ISSUE TITLE
Can't get slider working...

### ISSUE THREAD

**Issue by Helpmetoday** [CSS-Tricks/AnythingSlider#660]
Hello,

Can someone please help me get this working? Here's what I know: I am using the smarty template system and I have tried using literal tags around the js code. I believe the js is the issue but I don't know how to resolve.

Thank you
Brian

**Comment by Mottie** [comment]
Hi @Helpmetoday!

It would help if you share the code you're using and what in what order are you loading scripts? What version of jQuery are you using? Are you seeing any errors in the console?

Modify [this demo](http://plnkr.co/edit/MjtxrhxO3oM94iASmrx8?p=preview) with your code to see if it works for you. Make sure jQuery is loaded before the other scripts.

**Comment by JamyGolden** [comment]
Closing since it's been a few months.
